/**
 * @brief Description...
 *
 * Long description...
 * @file pointers.h
 * @author borjagilperez at github.com
 */

/**
 * @brief Description...
 *
 * Long description...
 * @param c character...
 * @return OK...
 */
int f1(char c);

/**
 * @brief Description...
 *
 * Long description...
 * @param pc character pointer
 * @return OK...
 */
int f2(char *pc);

/**
 * @brief Description...
 *
 * Long description...
 * @param ac character array...
 * @return OK...
 */
int f3(char *ac);

/**
 * @brief Description...
 *
 * Long description...
 * @param ac character array...
 * @return OK...
 */
int f4(char *ac);

/**
 * @brief Description...
 *
 * Long description...
 * @param ai integer array...
 * @param ac character array...
 * @return OK...
 */
int f5(int *ai, char* ac);

/**
 * @brief Description...
 *
 * Long description...
 * @param ac character array...
 * @return OK...
 */
int f6(char *ac);
